fix: update gpg keys

diff --git a/.github/workflows/desktoprelease.yml b/.github/workflows/desktoprelease.yml
--- a/.github/workflows/desktoprelease.yml
+++ b/.github/workflows/desktoprelease.yml
@@ -124,12 +124,16 @@ jobs:
           LINUX_SIGNING_KEY_ID: ${{ steps.import-key.outputs.LINUX_SIGNING_KEY_ID }}
           LINUX_SIGNING_KEY_PASSPHRASE: ${{ secrets.LINUX_SIGNING_KEY_PASSPHRASE }}
         run: |
+          set -e # Exit immediately if a command exits with a non-zero status.
+          
           # Sign the .deb file.
           for deb_file in src-tauri/target/release/bundle/deb/*.deb; do
+            echo "Signing deb file: $deb_file"
             gpg --batch --yes --pinentry-mode loopback --passphrase "$LINUX_SIGNING_KEY_PASSPHRASE" --armor --detach-sign --local-user "$LINUX_SIGNING_KEY_ID" "$deb_file"
           done
           # Sign the .AppImage file.
           for appimage_file in src-tauri/target/release/bundle/appimage/*.AppImage; do
+            echo "Signing AppImage file: $appimage_file"
             gpg --batch --yes --pinentry-mode loopback --passphrase "$LINUX_SIGNING_KEY_PASSPHRASE" --armor --detach-sign --local-user "$LINUX_SIGNING_KEY_ID" "$appimage_file"
           done
         shell: bash
